# .pre-commit-config.yaml
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.81.1  # (dernière version au 20 mai 2025)
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
