name: Branch name policy

on:
  push:
    # On déclenche ce workflow sur TOUTES les branches (ne pas utiliser branches-ignore)
    # Ou bien tu peux limiter à un pattern large comme '*'
    branches:
      - '*'

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Interdire push direct sur master
        if: ${{ github.ref_name == 'master' }}
        run: |
          echo "ERROR: Pushes directly on 'master' branch are forbidden."
          exit 1

      - name: Interdire branches qui ne commencent pas par 'rd/'
        if: ${{ !startsWith(github.ref_name, 'rd/') && github.ref_name != 'master' }}
        run: |
          echo "ERROR: Pushes are only allowed on branches starting with 'rd/'"
          exit 1
