# # .github/workflows/terraform.yml
# name: Terraform CI/CD

# on:
#   pull_request:
#     branches:
#       - master
#     paths:
#       - '**.tf'
#       - 'envs/**'
#   push:
#     branches:
#       - master
#     paths:
#       - '**.tf'
#       - 'envs/**'

# jobs:
#   validate:
#     name: Terraform Validate & Plan
#     runs-on: ubuntu-latest
#     if: startsWith(github.head_ref, 'rd/')
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v2
#         with:
#           terraform_version: 1.5.6

#       - name: Terraform Init
#         run: terraform init

#       - name: Terraform Validate
#         run: terraform validate

#       - name: Terraform Plan (dev)
#         run: terraform workspace select dev || terraform workspace new dev && terraform plan -var-file=envs/dev.tfvars

#       - name: Terraform Plan (prod)
#         run: terraform workspace select prod || terraform workspace new prod && terraform plan -var-file=envs/prod.tfvars

#   apply:
#     name: Terraform Apply on master
#     needs: validate
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/master'
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v2
#         with:
#           terraform_version: 1.5.6

#       - name: Terraform Init
#         run: terraform init

#       - name: Select dev workspace
#         run: terraform workspace select dev || terraform workspace new dev

#       - name: Terraform Apply dev
#         run: terraform apply -auto-approve -var-file=envs/dev.tfvars

#       - name: Select prod workspace
#         run: terraform workspace select prod || terraform workspace new prod

#       - name: Terraform Apply prod
#         run: terraform apply -auto-approve -var-file=envs/prod.tfvars
